project:
  type: website

execute: 
  freeze: auto

website:
  title: "Harriet Mason"
  navbar:
    background: primary
    search: true
    left:
      - href: posts/index.qmd
        text: Blog
      - href: teaching/index.qmd
        text: Teaching
      - href: talks/index.qmd
        text: Talks
        

format:
  html:
    theme: journal 
    from: markdown+emoji
