project:
  type: website 

execute: 
  freeze: auto

website:
  title: "Harriet Mason" 
  navbar:
    background: primary 
    search: true
    left:
      - href: posts/index.qmd
        text: Blog
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching Resources
      - href: CV/cv.pdf
        text: CV 
        

format:
  html:
    theme: journal 
    from: markdown+emoji
